name: Code Style

on:
#  pull_request:
#    branches:
#      - main
#      - develop
#      - 'release/**'
#      - 'feature/**'
#      - 'hotfix/**'
#      - 'fix/**'
#    paths-ignore:
#      - '**.md'

  # use workflow_dispatch for now to fine-tune code style configurations
  workflow_dispatch:
    inputs:
      php:
        required: true
        default: '8.2'
        description: 'Fix code style using PHP version'
        type: choice
        options:
          - '8.2'
          - '8.3'
      message:
        required: false
        description: 'Commit message for linted files'
        default: 'Fix code style'
      fix:
        required: false
        description: 'Fix code style issues'
        default: false

jobs:
  code_style:
    name: Code Style
    uses: noprotocol/.github/.github/workflows/php-coding-standards.yml@main
    with:
      php: ${{ inputs.php }}
      message: ${{ inputs.message }}
      fix: ${{ inputs.fix }}
