name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true

jobs:
  release:
    if: ${{ github.ref == 'refs/heads/main' }} # guard, only run workflow on main branch

    name: Github Release
    uses: noprotocol/.github/.github/workflows/release.yml@main
    with:
      version ${{ inputs.version }}
#    secrets:
#      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }} # defined at ORG level at Github (PAT)
