name: 'Generate release notes'
description: 'Generate release notes via Github API'

runs:
  using: 'node20'
  main: 'dist/index.js'

inputs:
  token:
    description: 'The GitHub token (GITHUB_TOKEN environment variable)'
    required: true
  tag_name:
    description: 'The tag name'
    required: true
  branch:
    description: 'The branch'
    required: false
    default: 'main'

outputs:
  release_notes:
    description: 'The release notes as string'
