name: 'Deploy to Heroku'
description: 'Deploy to Heroku from Github Actions'

runs:
  using: 'node20'
  main: 'dist/index.js'

inputs:
  api_key:
    description: 'Heroku API key'
    required: true
  app_name:
    description: 'Heroku App Name'
    required: true
  username:
    description: 'Github username'
    required: true
  email:
    description: 'Github email'
    required: true
  branch_or_tag:
    description: 'The branch or tag that is deployed to Heroku'
    required: true
  stack:
    description: 'Which Heroku stack to use, defaults to heroku-22'
    required: false
    default: 'heroku-22'
