name: Deploy to Heroku

on:
  workflow_call:

jobs:
  deploy_to_heroku:
    if: ${{ startsWith(github.ref, 'refs/tags/') }} # guard, only tags are allowed to be deployed

    runs-on: ubuntu-22.04

    name: Deploy ${{ github.ref_name }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Deploying ${{ github.ref_name }}
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_app_name: ${{ vars.HEROKU_APP_NAME }} # defined at REPO level at Github
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }} # defined at ORG level at Github
          heroku_email: ${{ vars.HEROKU_EMAIL }} # defined at ORG level at Github
          team: ${{ vars.HEROKU_ORG }} # defined at ORG level at Github
          branch: ${{ github.ref }} # refs/tags/v1.2.3
