name: Deploy to Heroku

on:
  workflow_call:
    secrets:
      HEROKU_API_KEY:
        description: 'API Key for Heroku API'
        required: false

jobs:
  deploy_to_heroku:
    if: ${{ startsWith(github.ref, 'refs/tags/') }} # guard, only tags are allowed to be deployed

    runs-on: ubuntu-22.04

    name: Deploy ${{ github.ref_name }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Log deployment
        run: echo 'Deployment started by ${{ github.actor }}'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }} # defined at ORG level at Github
          heroku_app_name: ${{ vars.HEROKU_APP_NAME }} # defined at REPO level at Github
          heroku_email: devops@noprotocol.nl
          team: ${{ vars.HEROKU_ORG }} # defined at ORG level at Github
          branch: ${{ github.ref }}
