name: Code Style

on:
  workflow_call:
    inputs:
      php:
        default: '8.2'
        type: string
      message:
        default: Fix code style
        type: string
      fix:
        default: true
        type: boolean

jobs:
  code_style:
    runs-on: ubuntu-22.04

    name: Code Style

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Laravel Pint
        run: composer global require laravel/pint

      - name: Run Laravel Pint
        run: pint --config code-style/php/pint.json

      - name: Commit linted files
        if: ${{ inputs.fix }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.message }}
