name: Static Analysis

on:
  workflow_call:
    inputs:
      php:
        default: '8.2'
        type: string
        required: false
      memory_limit:
        default: '512M'
        type: string
        required: false

jobs:
  phpstan:
    runs-on: ubuntu-22.04

    name: PHPStan

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2
          coverage: none

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install & Cache Composer Dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist"

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --ansi --memory-limit ${{ inputs.memory_limit }}
