name: Generate PHP Code Coverage Report

on:
  workflow_call:
    secrets:
      env_file:
        required: true
    inputs:
      php:
        default: '8.2'
        type: string

jobs:
  code_coverage:
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    name: Code Coverage

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: echo "${{ secrets.env_file }}" >> .env # defined at REPO level at Github

      - name: Read .env file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: '.env'
          mask: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2
          coverage: pcov

      - name: Install & Cache Composer Dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist"

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Generate Code Coverage
        run: php artisan test --parallel --coverage-html coverage

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ github.ref_name }}
          path: |
            coverage
            storage/logs
          retention-days: 1
